# 后端的项目配置文件, 将数据库密码改成自己的

spring:
  application:
    name: farm-search-backend

  datasource:
    url: jdbc:mysql://localhost:3306/farmsearch?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 273151
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.gala.farmsearchbackend.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.gala.farmsearchbackend.model.domain
  configuration:
    map-underscore-to-camel-case: true  # ????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL??

  redis:
    host: localhost
    port: 6379
    #password:
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
logging:
  level:
    com.gala.farmsearchbackend: DEBUG
    org.springframework.cache: TRACE